added py tests
dantol29/webserver pull request #232
Opened 2024-04-30 15:42 UTC by dantol29

## Added tests using Python

1. Header size > BUFFER_SIZE (atm return 200)
2. Header size > 8KB (atm return 431)
3. Chunked request (atm return 400)

2024-04-30 18:26 UTC, dantol29 commented
1 test sends header size more than BUFFER_SIZE, so it should be 200.

2 test sends header size more than 8KB, so it should be 431

3 test sends a chucked request, but our server does not handle them properly atm.

2024-05-01 09:30 UTC, dantol29 commented
## Added more tests + fixed file upload parsing

1. Test with file upload
2. Test with multiple file uploads
3. After testing I fixed parsing

2024-05-01 11:35 UTC, dantol29 commented
## Is it OK?

it took more than 5 minutes to upload a 30MB image and at the end it did not work

2024-05-01 11:45 UTC, dantol29 commented
## Large file is saved successfully if I do not check for CRLF, but in some requests content-length for the file is not provided and I have to know where the file ends and starts the next one. I have to think about it

2024-05-02 09:50 UTC, dantol29 commented
@552020 I merged main and python tester stopped working...

I rolled back and it seems to work again

2024-05-02 10:12 UTC, dantol29 commented
@552020 This branch is merged with the main, but the main does not work properly, even just localhost:8080 does not work

2024-05-02 10:37 UTC, 552020 commented
> @552020 This branch is merged with the main, but the main does not work properly, even just localhost:8080 does not work

Then we should open an urgent issue! ;-)

2024-05-04 08:20 UTC, 552020 commented
Are you going to fix it by yourself? Or you need help on this? @dantol29

2024-05-04 08:38 UTC, dantol29 commented
@552020 I think py tests are correct, the problem is in our webserver

2024-05-05 09:38 UTC, dantol29 commented
@552020 @lmangall ready to be merged!

2024-05-05 09:47 UTC, dantol29 commented
@lmangall When I upload multiple files with html I get this error from CGI. Files are saved and parsed correctly, but then it goes to CGI for some reason.

![image](https://github.com/dantol29/webserver/assets/83882235/a0438647-a842-4a4f-a4d1-72d97c209f1c)

2024-05-05 10:46 UTC, lmangall commented
Okay, it's pretty strange, only with multiple files ? Is the request differently formed for one or several files ? 
This is a request or router error. When I'll work on the response for an upload I'll check for that in parallel.
Can you open an issue ?

2024-05-05 10:48 UTC, lmangall commented
@dantol29  I am going through the PR, this branch is for both py tests AND upload (or large uploads ?), correct ?

2024-05-05 11:21 UTC, dantol29 commented
@lmangall Yes, for both tests and file upload. While I was testing file upload I found lots of issues and fixed them in the same branch.

2024-05-05 12:39 UTC, lmangall approved these changes
Please rename these few things and open issue(s) for the improvements

2024-05-05 12:39 UTC, lmangall commented on src/Server.cpp
> +			std::cout << "Error opening file" << std::endl;
The naming should be changed, in another PR we can set an error, perhaps:
422 Unprocessable Entity: This status code is more specific and indicates that the server understands the request's syntax but cannot process the instructions. This code may be used when the uploaded file is corrupted, lacks a name, or doesn't meet server requirements.

2024-05-05 12:39 UTC, lmangall commented on src/Server.cpp
> +			std::cout << "File created successfully" << std::endl;
I think we should have a boolean for that, it's an improvement so it can be in a next PR

2024-05-05 12:39 UTC, lmangall commented on tests/5mb.jpg
Reminds me of holidays, horrible, so better to be in 42!

2024-05-05 12:39 UTC, lmangall commented on tests/general_tests.py
Some comments would have been god with at least a couple comments :)

2024-05-05 12:40 UTC, lmangall requested changes
Sorry, I meant "Request Changes"

2024-05-05 16:51 UTC, dantol29 commented
@lmangall I fixed everything you requested + improved py tests a bit!

2024-05-05 17:08 UTC, lmangall submitted a review, later dismissed
LGTM

2024-05-05 18:27 UTC, 552020 approved these changes
LGTM!

2024-05-05 18:30 UTC, lmangall approved these changes
LGTM

2024-05-05 18:30 UTC, merged